language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
cache: cargo
addons:
  apt:
    packages:
    - libsdl2-dev
    - libasound2-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
